### ISSUE TITLE
Remember "Eat" option

### ISSUE THREAD

**Issue by 404Setup** [ItsThosea/EatServerPacks#2]
Every time you join the server, you will prompt "Eat" and need to choose manually.
Can you remember "Eat" and change it on the server editing page?

**Comment by imthosea** [comment]
This is the first time I've been notified of something with a repository other than BadOptimizations.

**Comment by imthosea** [comment]
Anyway, yeah, when I get home I'll try.

**Comment by imthosea** [comment]
<img src="https://github.com/ItsThosea/EatServerPacks/assets/104597976/fbb26070-f7d9-4f25-9802-1f38ef30cc7a" width=312>


<img src="https://github.com/ItsThosea/EatServerPacks/assets/104597976/7da4b797-30a8-4d6f-8c93-c959ab98bc05" width=312>


<img src="https://github.com/ItsThosea/EatServerPacks/assets/104597976/dc68ba02-4ea1-4579-8714-dc6bdac47b50"  width=312>


Not sure if I should keep the Save Eat Pack thing as it might get confusing and you can just go into this menu.

**Comment by imthosea** [comment]
A little late...?
