### ISSUE TITLE
[Feature Request] Copy pack link on shift click

### ISSUE THREAD

**Issue by zajdov** [ItsThosea/EatServerPacks#3]
Currently, opening browser will download the pack instanly making it very inconvenient if you want to get the URL.

Instead, I suggest primary copying the URL or adding a "copy pack link" button.

**Comment by imthosea** [comment]
But how would that work when multiple packs are sent?

**Comment by zajdov** [comment]
> But how would that work when multiple packs are sent?

I haven't encountered a server with multiple packs yet. What would happen currently if say, 7 packs are sent and the "Open Download Link" is clicked?

Are 7 browser instances launched or does each pack have its own confirmation screen?

**Comment by ItsThosea** [comment]
> Are 7 browser instances launched or does each pack have its own confirmation screen?

Yes lmfao

**Comment by imthosea** [comment]
> Are 7 browser instances launched or does each pack have its own confirmation screen?

Yes lmfao

**Comment by imthosea** [comment]
Well, actually 7 \*tabs\*.

**Comment by zajdov** [comment]
could just separate the download links with LF and copy the whole thing?

**Comment by imthosea** [comment]
LF? I assume that's a line break, in that case you read my mind.

**Comment by zajdov** [comment]
yes, add a new line

**Comment by imthosea** [comment]
Give this a shot: [mod.zip](https://github.com/user-attachments/files/17320126/mod.zip)
I'll fix pack policies another time

**Comment by zajdov** [comment]
Works well, thank you!

**Comment by imthosea** [comment]
Wait don't close it til I release

**Comment by imthosea** [comment]
released
