### ISSUE TITLE
Eat Pack option fails server-side detection

### ISSUE THREAD

**Issue by zajdov** [ItsThosea/EatServerPacks#4]
Servers (like OriginRealms) that run custom logic based on bukkit's PlayerResourcePackStatusEvent seem not to be receiving ACCEPTED or SUCCESSFULLY_LOADED, making the client wait indefinitely or, in some cases, straight up disconnecting it.

This occurs when the "Server Resource Packs:" option on the "Edit Server Info" screen is set to "Eat Pack"

Version: 1.2.0 (1.21)

**Comment by imthosea** [comment]
I only really tested this on MCCI. Does it work if you don't set the option and click the button manually?

**Comment by zajdov** [comment]
> I only really tested this on MCCI. Does it work if you don't set the option and click the button manually?

yes, manually works as expected.

**Comment by imthosea** [comment]
Ok, I think I found the issue. Does this work?
[mod.zip](https://github.com/user-attachments/files/17335824/mod.zip)

**Comment by zajdov** [comment]
Yep, works perfectly. Thanks to your mod, I found a solution to the long RP loading for servers that I visit regularly by downloading the pack, applying it globally and then eating it on each visit.

Huge Thanks!

**Comment by imthosea** [comment]
Great, now the fun part...backporting.

**Comment by imthosea** [comment]
My goodness the new modrinth UI sucks.
Anyhow, the versions are out now.
